In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

In [2]:
jumbo_raw = pd.read_csv("../Data/Raw/jumbo_product_data.csv")
plus_raw = pd.read_csv("../Data/Raw/plus_product_data.csv")

In [3]:
print(jumbo_raw.shape)
print(jumbo_raw.dtypes)
print(jumbo_raw.info())

(220, 14)
Source_File         str
Date_Added          str
Supermarket         str
Product_Category    str
Product_ID          str
Product_Name        str
Product_Price       str
Price_Per_Unit      str
Energy_kj_100_g     str
Fats_100_g          str
Carbs_100_g         str
Sugars_100_g        str
Protein_100_g       str
Salt_100_g          str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Source_File       220 non-null    str
 1   Date_Added        220 non-null    str
 2   Supermarket       220 non-null    str
 3   Product_Category  220 non-null    str
 4   Product_ID        220 non-null    str
 5   Product_Name      220 non-null    str
 6   Product_Price     220 non-null    str
 7   Price_Per_Unit    220 non-null    str
 8   Energy_kj_100_g   187 non-null    str
 9   Fats_100_g        163 non-null    str
 10  Carbs_100_g       187 non-null    str
 11  Sugars_100_g      163 non-null    str
 12  Protein_100_g     180 non-null    str
 13  Salt_100_g        155 non-null    str
dtypes: str(14)
memory usage: 24.2 KB
None

In [4]:
jumbo_clean = jumbo_raw.copy()
jumbo_clean['Date_Added'] = pd.to_datetime(jumbo_raw['Date_Added'].copy()).dt.date

jumbo_clean.head()

,Source_File,Date_Added,Supermarket,Product_Category,Product_ID,Product_Name,Product_Price,Price_Per_Unit,Energy_kj_100_g,Fats_100_g,Carbs_100_g,Sugars_100_g,Protein_100_g,Salt_100_g
0,activia-yoghurt-aardbei-4-x-125-g-228598STK.html,2026-06-23,Jumbo,Yoghurt,228598STK,Activia Yoghurt Aardbei 4 x 125 g,"Prijs: € 2,99 2 99","€ 5,98 per kilo 5,98 / kilo",372.0 kJ,2.8 g,12.0 g,11.7 g,3.7 g,0.13 g
1,activia-yoghurt-granen-4-x-125-g-302972STK.html,2026-06-23,Jumbo,Yoghurt,302972STK,Activia Yoghurt Granen 4 x 125 g,"Prijs: € 2,99 2 99","€ 5,98 per kilo 5,98 / kilo",379.0 kJ,2.9 g,11.3 g,10.5 g,3.9 g,0.1 g
2,activia-yoghurt-muesli-4-x-125-g-302975STK.html,2026-06-23,Jumbo,Yoghurt,302975STK,Activia Yoghurt Muesli 4 x 125 g,"Prijs: € 2,89 2 89","€ 5,78 per kilo 5,78 / kilo",392.0 kJ,2.9 g,12.0 g,10.7 g,3.9 g,0.1 g
3,activia-yoghurt-naturel-4-x-125-g-491422TUB.html,2026-06-23,Jumbo,Yoghurt,491422TUB,Activia Yoghurt Naturel 4 x 125 g,"Prijs: € 2,39 2 39","€ 4,78 per kilo 4,78 / kilo",276.0 kJ,3.5 g,4.7 g,4.7 g,3.9 g,0.1 g
4,activia-yoghurt-pruim-4-x-125-g-709840PAK.html,2026-06-23,Jumbo,Yoghurt,709840PAK,Activia Yoghurt Pruim 4 x 125 g,"Prijs: € 2,89 2 89","€ 5,78 per kilo 5,78 / kilo",414.0 kJ,3.4 g,12.9 g,12.0 g,3.4 g,0.1 g

In [14]:
#removing spaces from the product name
name_text = jumbo_clean['Product_Name'].iloc[0]
new_name = name_text.replace(' ','_')
print(new_name)

#obtaining product brand
Brand = jumbo_clean['Product_Name'].iloc[0].split('_')[0]
print(Brand)

#Extracting just the price
price_text = jumbo_clean['Product_Price'].iloc[0]
product_price = float(price_text
                    .split(' ')[1]
                    .split("\xa0")[1]
                    .replace(",", '.'))
print(product_price)

price_unit_text = jumbo_clean['Price_Per_Unit'].iloc[0]
unit_price = float(price_unit_text
                 .split(' ')[3]
                 .replace(",", '.'))
print(unit_price)

#calculating the weight of a product
weight_in_g = product_price / unit_price * 1000
print(weight_in_g)

#converting energy to kcal instead of kJ
energy_text = jumbo_clean['Energy_kj_100_g'].iloc[0]
energy_kJ = float(energy_text
                 .split(' ')[0])
energy_kcal = round((energy_kJ / 4.184) ,1)

print(energy_kcal)


nutrient_categories = jumbo_clean.columns[8:]

for nutrient in nutrient_categories:
    nutrient_name = nutrient.split("_")[0]
    multiple_of_100_g = float(weight_in_g / 100)
    # f"{nutrient_name}_In_Product" = int(jumbo_clean[nutrient].split(" ")[0]) * multiple_of_100_g
    nutrients_in_product = float(jumbo_clean[nutrient].iloc[0].split(" ")[0]) * multiple_of_100_g
    print(f"{nutrients_in_product} grams of {nutrient_name}")

Activia_Yoghurt_Aardbei_4_x_125_g
Activia
2.99
5.98
500.0
88.9
1860.0 grams of Energy
14.0 grams of Fats
60.0 grams of Carbs
58.5 grams of Sugars
18.5 grams of Protein
0.65 grams of Salt

In [17]:
jumbo_final = pd.read_csv(r"C:\Users\maxde\03.Scraping_and_Analysis_automated\Data\Processed\jumbo_product_data_clean.csv")

jumbo_final.head()

,Source_File,Date_Added,Supermarket,Product_Category,Product_ID,Product_Name,Product_Price,Price_Per_Unit,Energy_kj_100_g,Fats_100_g,...,Brand,Product_Price_Clean,Price_Per_Unit_Clean,Weight_g,Energy_kcal_100_g,Fats_In_Product_g,Carbs_In_Product_g,Sugars_In_Product_g,Protein_In_Product_g,Salt_In_Product_g
0,activia-yoghurt-aardbei-4-x-125-g-228598STK.html,2026-06-23,Jumbo,Yoghurt,228598STK,Activia Yoghurt Aardbei 4 x 125 g,"Prijs: € 2,99 2 99","€ 5,98 per kilo 5,98 / kilo",372.0 kJ,2.8 g,...,Activia,2.99,5.98,500.0,88.9,14.0,60.0,58.5,18.5,0.65
1,activia-yoghurt-granen-4-x-125-g-302972STK.html,2026-06-23,Jumbo,Yoghurt,302972STK,Activia Yoghurt Granen 4 x 125 g,"Prijs: € 2,99 2 99","€ 5,98 per kilo 5,98 / kilo",379.0 kJ,2.9 g,...,Activia,2.99,5.98,500.0,90.6,14.5,56.5,52.5,19.5,0.50
2,activia-yoghurt-muesli-4-x-125-g-302975STK.html,2026-06-23,Jumbo,Yoghurt,302975STK,Activia Yoghurt Muesli 4 x 125 g,"Prijs: € 2,89 2 89","€ 5,78 per kilo 5,78 / kilo",392.0 kJ,2.9 g,...,Activia,2.89,5.78,500.0,93.7,14.5,60.0,53.5,19.5,0.50
3,activia-yoghurt-naturel-4-x-125-g-491422TUB.html,2026-06-23,Jumbo,Yoghurt,491422TUB,Activia Yoghurt Naturel 4 x 125 g,"Prijs: € 2,39 2 39","€ 4,78 per kilo 4,78 / kilo",276.0 kJ,3.5 g,...,Activia,2.39,4.78,500.0,66.0,17.5,23.5,23.5,19.5,0.50
4,activia-yoghurt-pruim-4-x-125-g-709840PAK.html,2026-06-23,Jumbo,Yoghurt,709840PAK,Activia Yoghurt Pruim 4 x 125 g,"Prijs: € 2,89 2 89","€ 5,78 per kilo 5,78 / kilo",414.0 kJ,3.4 g,...,Activia,2.89,5.78,500.0,98.9,17.0,64.5,60.0,17.0,0.50

In [19]:
plus_raw.head()

,Source_File,Date_Added,Supermarket,Product_Category,Product_ID,Product_Name,Product_Price,Price_Per_Unit,Energy_kj_100_g,Fats_100_g,Carbs_100_g,Sugars_100_g,Protein_100_g,Salt_100_g
0,154058.json,2026-06-24 13:18:54.208717,Plus,Yoghurt,154058,Melkan Yoghurt snack banaan,1.49,7.45,405.0,3.3,13.2,11.3,3.4,0.15
1,155099.json,2026-06-24 13:18:54.208972,Plus,Yoghurt,155099,Campina Halfvolle milde yoghurt,1.89,1.89,206.0,1.5,3.8,3.8,4.0,0.11
2,155129.json,2026-06-24 13:18:54.209194,Plus,Yoghurt,155129,Campina Magere yoghurt,1.69,1.69,161.0,0.0,3.7,3.7,4.4,0.12
3,155170.json,2026-06-24 13:18:54.209402,Plus,Yoghurt,155170,Campina Vanille yoghurt,1.99,1.99,317.0,1.6,11.0,10.0,3.1,0.09
4,155323.json,2026-06-24 13:18:54.209592,Plus,Yoghurt,155323,Campina Volle yoghurt,1.95,1.95,262.0,3.1,3.7,3.7,3.9,0.11